# Generated by Django 4.2.11 on 2026-05-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_options_post_unique_author_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_author_slug',
        ),
    ]
